---
- name: Install Docker and Docker Compose
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      package:
        name:
          - curl
          - git
          - python3
        state: present
      when: ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'apk' or ansible_pkg_mgr == 'apt'

    - name: Check if Docker is installed
      command: docker --version && echo 0 || echo 1
      register: docker_version
      ignore_errors: true

    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | bash
      args:
        warn: false
        executable: /bin/bash
      when: ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'apk' and docker_version.rc != 0

    - name: Install Docker
      apt:
        name: docker.io
        state: latest
      when: ansible_pkg_mgr == 'apt' and docker_version.rc != 0

    - name: Install Docker Compose
      shell: curl -sSL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m) -o /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose
      args:
        executable: /bin/bash

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
      when: docker_version.rc != 0
