- name: Configure I2C and install Oled drivers Uctronic
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes      
      
    - name: Install dependencies
      apt:
        name:
          - git

    - name: Replace dtparam
      lineinfile:
        path: /boot/config.txt
        regexp: '^dtparam='
        line: '#dtparam=\ndtparam=i2c_arm=on'

    - name: Clone the Git repository
      become: true
      git:
        repo: https://github.com/UCTRONICS/U6143_ssd1306.git
        dest: /opt/U6143_ssd1306
        force: yes

    - name: Build the display program
      become: true
      shell: make clean && make
      args:
        chdir: /opt/U6143_ssd1306/C

    - name: Copy the executable
      become: true
      copy:
        src: /opt/U6143_ssd1306/C/display
        dest: /usr/local/bin/
        mode: "0755"

    - name: Copy the systemd service file
      become: true
      copy:
        src: /opt/U6143_ssd1306/contrib/U6143_ssd1306.service
        dest: /etc/systemd/system/
        mode: "0644"

    - name: Reload systemd
      become: true
      systemd:
        daemon_reload: yes

    - name: Enable the service
      become: true
      systemd:
        name: U6143_ssd1306.service
        enabled: yes

    - name: Start the service
      become: true
      systemd:
        name: U6143_ssd1306.service
        state: started
